#' Create a New Tatami App
#'
#' Scaffolds a new Quarto dashboard project with the tatami directory structure.
#' Creates all necessary files and folders for a modular Quarto dashboard,
#' including a sample module, configuration, and tests.
#'
#' @param path Path to the directory where the app should be created.
#' @param open Whether to open the new project. Defaults to `TRUE` in
#'   interactive sessions.
#'
#' @return The path to the created app (invisibly).
#'
#' @export
create_app <- function(path, open = interactive()) {
    path <- normalizePath(path, mustWork = FALSE)
    app_name <- basename(path)

    if (dir.exists(path)) {
        stop("Directory already exists: ", path, call. = FALSE)
    }

    dir.create(path, recursive = TRUE)
    dir.create(file.path(path, "R"))
    dir.create(file.path(path, "man"))
    dir.create(file.path(path, "inst", "assets", "css"), recursive = TRUE)
    dir.create(file.path(path, "inst", "assets", "img"), recursive = TRUE)
    dir.create(file.path(path, "tests", "testthat"), recursive = TRUE)

    writeLines(description_template(app_name), file.path(path, "DESCRIPTION"))
    writeLines(namespace_template(), file.path(path, "NAMESPACE"))
    writeLines(package_r_template(app_name), file.path(path, "R", paste0(app_name, "-package.R")))
    writeLines(run_r_template(), file.path(path, "R", "run.R"))
    writeLines(context_data_r_template(), file.path(path, "R", "context_data.R"))
    writeLines(config_r_template(), file.path(path, "R", "config.R"))
    writeLines(index_qmd_template(), file.path(path, "index.qmd"))
    writeLines(config_yml_template(), file.path(path, "inst", "config.yml"))
    writeLines(brand_yml_template(), file.path(path, "inst", "_brand.yml"))
    writeLines(gitignore_template(), file.path(path, ".gitignore"))
    writeLines(rbuildignore_template(), file.path(path, ".Rbuildignore"))
    writeLines(testthat_r_template(app_name), file.path(path, "tests", "testthat.R"))
    file.create(file.path(path, "inst", "assets", "css", ".gitkeep"))
    file.create(file.path(path, "inst", "assets", "img", ".gitkeep"))

    message("tatami app created at: ", path)

    if (open && requireNamespace("rstudioapi", quietly = TRUE)) {
        if (rstudioapi::isAvailable()) {
            rstudioapi::openProject(path, newSession = TRUE)
        }
    }

    invisible(path)
}

description_template <- function(app_name) {
    c(
        paste0("Package: ", app_name),
        paste0("Title: A Tatami Quarto Dashboard"),
        "Version: 0.0.0.9000",
        paste0("Description: A modular Quarto dashboard built with tatami."),
        "License: MIT + file LICENSE",
        "Encoding: UTF-8",
        "Roxygen: list(markdown = TRUE)",
        "Imports: ",
        "    shiny,",
        "    quarto,",
        "    config,",
        "    tatami",
        "Suggests: ",
        "    pkgload,",
        "    testthat (>= 3.0.0)",
        "Config/testthat/edition: 3"
    )
}

namespace_template <- function() {
    c(
        "# Generated by roxygen2: do not edit by hand",
        "",
        "export(context_data)",
        "export(get_config)",
        "export(run_app)",
        "import(shiny)",
        "import(htmltools)",
        "import(bslib)",
        "importFrom(pkgload,load_all)",
        "importFrom(quarto,quarto_serve)"
    )
}

package_r_template <- function(app_name) {
    c(
        "#' @keywords internal",
        "#' @import shiny",
        "#' @import htmltools",
        "#' @import bslib",
        paste0('"_PACKAGE"'),
        "",
        "## usethis namespace: start",
        "#' @importFrom pkgload load_all",
        "#' @importFrom quarto quarto_serve",
        "## usethis namespace: end",
        "NULL"
    )
}

run_r_template <- function() {
    c(
        "#' Run App",
        "#'",
        "#' @param production Logical; if TRUE, uses production configuration.",
        "#' @param ... Additional parameters to pass to [quarto::quarto_serve].",
        "#'",
        "#' @export",
        "run_app <- function(production = FALSE, ...) {",
        "\tif (production) {",
        "\t\tSys.setenv(\"R_CONFIG_ACTIVE\" = \"production\")",
        "\t} else {",
        "\t\tSys.setenv(\"R_CONFIG_ACTIVE\" = \"default\")",
        "\t}",
        "\tquarto::quarto_serve(\"index.qmd\", ...)",
        "}"
    )
}

context_data_r_template <- function() {
    c(
        "#' Context Data Function",
        "#'",
        "#' @export",
        "context_data <- function() {",
        "    # Assign objects via <<- to make them available in global environment",
        "    vars <<- setdiff(names(iris), \"Species\")",
        "}"
    )
}

config_r_template <- function() {
    c(
        "#' Get Configuration",
        "#'",
        "#' @param file Path to the configuration file.",
        "#'",
        "#' @return A list of configuration values for the active profile.",
        "#'",
        "#' @export",
        "get_config <- function(file = \"inst/config.yml\") {",
        "    config::get(file = file)",
        "}"
    )
}

index_qmd_template <- function() {
    c(
        "---",
        "title: \"My Dashboard\"",
        "format: dashboard",
        "server: shiny",
        "brand: inst/_brand.yml",
        "---",
        "",
        "```{r}",
        "#| context: setup",
        "pkgload::load_all()",
        "",
        "config <- get_config()",
        "```",
        "",
        "```{r}",
        "#| context: data",
        "context_data()",
        "```",
        "",
        "```{r}",
        "#| context: server",
        "```"
    )
}

config_yml_template <- function() {
    c(
        "default:",
        "  greeting: \"Hello, world!\"",
        "",
        "production:",
        "  greeting: \"Hey there!\""
    )
}

brand_yml_template <- function() {
    c(
        "color:",
        "  primary: black",
        "",
        "typography:",
        "  fonts:",
        "    - family: Open Sans",
        "      source: google",
        "  base: Open Sans",
        "  headings: Open Sans"
    )
}

gitignore_template <- function() {
    c(
        ".Rproj.user",
        "index.html",
        "/index_data",
        "/index_files"
    )
}

rbuildignore_template <- function() {
    c(
        "^.*\\.Rproj$",
        "^\\.Rproj\\.user$",
        "^LICENSE\\.md$",
        "^index\\.html$",
        "^index_data$",
        "^index_files$"
    )
}

testthat_r_template <- function(app_name) {
    c(
        "library(testthat)",
        paste0("library(", app_name, ")"),
        "",
        paste0("test_check(\"", app_name, "\")")
    )
}
